ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :unit_test do |options|
    run_tests(
      workspace: "App/MyAnimeList.xcworkspace",
      scheme: "Development",
      devices: ['iPhone 14 (16.2)'],
      build_for_testing: true,
      derived_data_path: "Build/",
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
  end
end
