name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@v3
      
      - name: "Check Applications List"
        run: ls -la /Applications/
      
      - name: "Change Xcode Version to 14.2"
        run: sudo xcode-select --switch /Applications/Xcode_14.2.app
      
      - name: UnitTests
        run: xcodebuild test -workspace ${GITHUB_WORKSPACE}/App/MyAnimeList.xcworkspace/ -scheme Development -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
